config/routes.rb
DemoApp::Application.routes.draw do
  resources :payments

  resources :orders

  get 'success' => 'payments#successfull'

  resources :line_items

  resources :carts

  root 'products#index'

  namespace :admin do
    resources :products
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/new' => 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

resources :products
namespace :admin do
end

end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  has_many :line_items

  def add_line_items_from_cart(cart)
      cart.line_items.each do |item|
        item.cart_id = nil
        line_items << item
      end
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate page: params[:page], order: 'created_at desc', per_page: 10
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @items = @order.line_items.product
  end

  # GET /orders/new
  def new

    @cart = current_cart
       if @cart.line_items.empty?
       redirect_to products_url, notice: "Your cart is empty"
       return
      end
      @order = Order.new
      respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @order }
          end

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(current_cart)
    respond_to do |format|
        if @order.save
          format.html { redirect_to new_payment_path(order: @order.id) }
          format.json { render json: @order, status: :created, location: @order }
        else
          @cart = current_cart
          format.html { render action: 'new' }
          format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_edit.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40, :required => true %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3, cols: 40, :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, size: 40, :required => true %>
  </div>
  <div class="field">
<%= f.label :pay_type %><br />
 <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: 'Select a payment method' %>
</div>
  <div class="actions">
    <%= f.submit 'Update', :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/orders/_form.html.erb
<div class="form-style-6">
<h1>Please Enter Your Details</h1>
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40, :required => true, :placeholder=>"Your Name" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3, cols: 40, :required => true, :placeholder=>"Address" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, size: 40, :required => true, :placeholder=>"Email Address" %>
  </div>
  <div class="field">
<%= f.label :pay_type %><br />
 <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: 'Select a payment method' %>
</div>
  <%#= button_to "Payment", payment_order_path, method: :post %>
  <div class="actions">
    <%= f.submit 'Proceed to Payment', :class=>"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'edit' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>



<div class="bs-example">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th>Pay type</th>
          </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= order.name %></td>
                <td><%= order.address %></td>
                <td><%= order.email %></td>
                <td><%= order.pay_type %></td>
                <td><%= link_to 'Show', order %></td>
                <td><%= link_to 'Edit', edit_order_path(order) %></td>
                <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <p><%= will_paginate @orders %></p>
      </div>
    </div>
  </div>
</div>
<br>

app/views/orders/new.html.erb
<div class="depot_form">
<fieldset>

<%= render 'form' %>
</fieldset>
</div>

app/views/orders/payment.html.erb
Pay now

<%= form_tag({controller: 'order', action: 'pay'}, method: :post) do |f| %>
<div class="field">
  <%= f.label :cc_number %><br>
  <%= f.text_field :cc_number, maxlength: 20, :required => true %>
</div>
<div class="field">
  <%= f.label :cc_cvc %><br>
  <%= f.text_field :cc_cvc, maxlength: 20, :required => true %>
</div>
<div class="field">
  <%= f.label :cc_exp_month %><br>
  <%= f.text_field :cc_exp_month, maxlength: 20, :required => true %>
</div>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>