config/routes.rb
DemoApp::Application.routes.draw do
  resources :payments

  resources :orders

  get 'success' => 'payments#successfull'

  resources :line_items

  resources :carts

  root 'products#index'

  namespace :admin do
    resources :products
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/new' => 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

resources :products
namespace :admin do
end

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    validates :title,:description , :price , :image , :available, presence: true
    validates :title, length: { minimum: 5 , maximum: 70 }
    scope :available_products, -> { where(available: true)   }

    has_many :line_items
    has_many :orders, through: :line_items
     before_destroy :check_if_proudct_in_cart

     private

     def ensure_not_referenced_by_any_line_item
              if line_items.empty?
                  return true
               else
                   errors.add(:base, 'Line Items is present!!')
                   return false
               end
     end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /admin/products
  # GET /admin/products.json
  def index
    @products = Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin ,@product ], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product =Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :available ,:image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.available_products
    @cart = current_cart
  end

  def create
    Product.create(title: params[:title], description: params[:description], image_url: params[:image_url], price: params[:price])
    flash[:notice] = "Product successfully created"
    redirect_to '/admin/products'
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin , @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title  , :required => true%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , :required => true%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price , :required => true %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available , :required => true%>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="bs-example">
  <td><%= link_to 'Add Proudct' , new_admin_product_path,:class=>"btn btn-primary show-btn"  %></td>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table">
          <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>description</th>
            <th>price</th>
          </tr>
          </thead>
          <tbody>
          <% @products.each do |i|%>
              <tr>
                <td><%=image_tag i.image.url(:thumb)%></td>
                <td><%= i.title%></td>
                <td><%= i.description%></td>
                <td><%= i.price%></td>

                <td><%= link_to 'Show' , admin_product_path(i.id),:class=>"btn btn-primary show-btn"  %></td>
                <td><%= link_to 'Edit' , edit_admin_product_path(i.id),:class=>"btn btn-primary show-btn"  %></td>
                <td><%= link_to 'Delete' , admin_product_path(i.id),:class=>"btn btn-primary show-btn" , :confirm => 'Are you sure' , :method => 'delete'%></td>

              </tr>
          <% end %>
          </tbody>
        </table>
       </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path ,:class=>"btn btn-primary show-btn"%>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag (@product.image.url(:thumb)) %>
</p>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) ,:class=> "btn btn-primary show-btn"%> |
<%= link_to 'Back', admin_products_path ,:class=> "btn btn-primary show-btn" %>